### ISSUE TITLE
I guess this should get converted to Dart now ;-)

### ISSUE THREAD

**Issue by gmosx** [dart-lang/dartbug.com#2]

**Comment by sethladd** [comment]
yup! Help wanted :)

**Comment by gmosx** [comment]
Well, this seems pretty easy. Will try to do it over the upcoming w/e.

On Tue, May 26, 2015 at 8:56 PM, Seth Ladd <notifications@github.com> wrote:

> yup! Help wanted :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartbug.com/issues/2#issuecomment-105618195>
> .
>



-- 
http://www.gmosx.com

**Comment by sgjesse** [comment]
CL: https://codereview.chromium.org/1155243003/

**Comment by gmosx** [comment]
@sgjesse wow, elegant implementation. I actually converted the python code last night, but your's is much better. Especially like Uri.resolve() and tests ;-)

**Comment by sgjesse** [comment]
Thanks George. Sorry for taking this issue, but I did not notice that you
have volunteered until I had done the implementation.

**Comment by gmosx** [comment]
np, keep up the great work man!

On Thu, May 28, 2015 at 10:53 AM, Søren Gjesse <notifications@github.com>
wrote:

> Thanks George. Sorry for taking this issue, but I did not notice that you
> have volunteered until I had done the implementation.
>
> On Wed, May 27, 2015 at 8:41 PM, George Moschovitis <
> notifications@github.com> wrote:
>
> > @sgjesse <https://github.com/sgjesse> wow, elegant implementation. I
> > actually converted the python code last night, but your's is much better.
> > Especially like Uri.resolve() and tests ;-)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/dart-lang/dartbug.com/issues/2#issuecomment-106028027>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartbug.com/issues/2#issuecomment-106218330>
> .
>



-- 
http://www.gmosx.com
